name: Go

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Get dependencies
      run: go get -v -t -d ./...

    - name: Go Build
      run: env GOOS=linux go build -ldflags="-s -w" -o bin/telegram telegram/main.go

    - name: SLS Deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}